### ISSUE TITLE
dist-поставка alfa-bank ui bem-components

### ISSUE THREAD

**Issue by Baskins** [alfa-bank-dev/ui#49]
Добрый день.
Не хотите рассмотреть вариант dist-поставки ваших блоков?
Аналог этого ишью https://github.com/bem/bem-forum-content-ru/issues/469

**Comment by awinogradov** [comment]
Таки у нас есть такой способ использования ;) Вот таск про это https://github.com/alfa-bank-dev/ui/blob/master/.enb/tasks/dist.js. Пока еще не успели завести репозиторий с собрынными асетами. Ишью даже есть https://github.com/alfa-bank-dev/ui/issues/7

**Comment by Baskins** [comment]
А сорри не заметил, закрываем тогда в пользу #7
спасибо
