### ISSUE TITLE
common.blocks/footer->additional не рисовать если не используется

### ISSUE THREAD

**Issue by lavcraft** [alfa-bank-dev/ui#51]
В случае `additional: ''` или `additional: false` срабатывает условие и ставится дефолтная надпись. 
А в случае `additional: ' '` рисуется пустой и **ненужный** блок

**Comment by voischev** [comment]
:+1:

**Comment by awinogradov** [comment]
А как надо?

**Comment by voischev** [comment]
Ну если поле пустое то вообще не рисовать этот элемент

**Comment by awinogradov** [comment]
ок
