### ISSUE TITLE
margins for form-field__label and fieldset__legend 

### ISSUE THREAD

**Issue by COOLek** [alfa-bank-dev/ui#55]
У элементов `form-field__label` и `fieldset__legend` при проставленном модификаторе  `{ view: 'line' }` у компонента отсутствуют отступы справа.

**Comment by awinogradov** [comment]
@COOLek было бы не лишним увидеть картинку. Пока не ясно в чем именно проблема.

**Comment by COOLek** [comment]
@awinogradov [example](https://dl.dropboxusercontent.com/u/56638965/Screen%20Shot%202016-03-04%20at%2013.58.29.png)

**Comment by awinogradov** [comment]
@COOLek пришли код, который это строит, плиз

**Comment by COOLek** [comment]
@awinogradov на демо-странице  `/pages/forms/forms.html` это прекрасно видно, если удлинить заголовок. [вот](https://dl.dropboxusercontent.com/u/56638965/Screen%20Shot%202016-03-04%20at%2014.17.53.png)

**Comment by awinogradov** [comment]
Ок! Теперьп понятно, спасибо! Поправим. Сейчас можно сделать правый отступ у блока внутри `fieldset__legend`

**Comment by voischev** [comment]
fix https://github.com/alfa-bank-dev/ui/pull/56
