### ISSUE TITLE
I have little problem with npm start

### ISSUE THREAD

**Issue by Prestapro** [alfa-bank-dev/ui#67]
Screen:
http://prntscr.com/ard432

Error log:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.5.3
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle ui@5.0.0-rc3~prestart: ui@5.0.0-rc3
7 silly lifecycle ui@5.0.0-rc3~prestart: no script for prestart, continuing
8 info lifecycle ui@5.0.0-rc3~start: ui@5.0.0-rc3
9 verbose lifecycle ui@5.0.0-rc3~start: unsafe-perm in lifecycle true
10 verbose lifecycle ui@5.0.0-rc3~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/PC/Desktop/server/ui/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
11 verbose lifecycle ui@5.0.0-rc3~start: CWD: /Users/PC/Desktop/server/ui
12 silly lifecycle ui@5.0.0-rc3~start: Args: [ '-c', 'enb server' ]
13 silly lifecycle ui@5.0.0-rc3~start: Returned: code: 1  signal: null
14 info lifecycle ui@5.0.0-rc3~start: Failed to exec start script
15 verbose stack Error: ui@5.0.0-rc3 start: `enb server`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
15 verbose stack     at EventEmitter.emit (events.js:110:17)
15 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at ChildProcess.emit (events.js:110:17)
15 verbose stack     at maybeClose (child_process.js:1015:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
16 verbose pkgid ui@5.0.0-rc3
17 verbose cwd /Users/PC/Desktop/server/ui
18 error Darwin 15.0.0
19 error argv "node" "/usr/local/bin/npm" "start"
20 error node v0.12.7
21 error npm  v3.5.3
22 error code ELIFECYCLE
23 error ui@5.0.0-rc3 start: `enb server`
23 error Exit status 1
24 error Failed at the ui@5.0.0-rc3 start script 'enb server'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the ui package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     enb server
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs ui
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls ui
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by awinogradov** [comment]
@Prestapro как видно из скрина, установка прошла неудачно. Попробуй руками устнавить vow.

**Comment by voischev** [comment]
Можно закрывать ишью?
